SRC := "com"
OUT := "out"
MAIN := "com.neowsl.lox.Lox"
GENERATE_AST := "com.neowsl.tool.GenerateAst"

build:
    javac -d {{OUT}} $(find {{SRC}} -name '*.java')

exec: build
    java -cp {{OUT}} {{MAIN}}

generate_ast:
    rm com/neowsl/lox/Expr.java
    just build
    java -cp {{OUT}} {{GENERATE_AST}} com/neowsl/lox
